import LegalPage, { Bullet, Paragraph, Section } from '../components/LegalPage';

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <Paragraph>
        These terms govern your use of Ollie. By creating an account or using the app, you agree to them. If you
        don't agree, please don't use Ollie.
      </Paragraph>

      <Section title="What Ollie is">
        <Bullet>
          Ollie is an AI companion app. Everything Ollie says is generated by an AI model — Ollie is not a real
          person, not a licensed therapist or counselor, and not a medical, legal, or financial professional.
        </Bullet>
        <Bullet>
          Ollie is built for everyday companionship and emotional support, not as a substitute for professional
          care. Nothing Ollie says should be taken as medical, mental health, legal, or financial advice.
        </Bullet>
      </Section>

      <Section title="Not a crisis service">
        <Bullet>
          Messages are automatically screened for signs of self-harm, abuse, or crisis, and Ollie is designed to
          respond with care and point toward real help when that happens — but Ollie is not an emergency service and
          this screening is not a guarantee.
        </Bullet>
        <Bullet>
          If you are in crisis or facing an emergency, contact local emergency services or a crisis line directly. Do
          not rely on Ollie for anything time-critical or life-threatening.
        </Bullet>
      </Section>

      <Section title="Who can use Ollie">
        <Bullet>You must be at least 13 years old to use Ollie.</Bullet>
        <Bullet>
          You're responsible for the accuracy of the information you provide when creating an account, and for
          keeping your password secure.
        </Bullet>
      </Section>

      <Section title="Free tier & Premium">
        <Bullet>
          The free tier includes a limited number of messages per day. Premium subscriptions (monthly or yearly)
          remove that limit and unlock additional features.
        </Bullet>
        <Bullet>
          Subscriptions are billed and managed through Lemon Squeezy, our Merchant of Record — it's the legal seller
          on every purchase. Auto-renewing subscriptions renew automatically until cancelled — cancel any time using
          the link in your receipt email. Refunds are handled under Lemon Squeezy's own refund policy, not directly
          by us.
        </Bullet>
        <Bullet>
          Prices and what's included in each tier may change; we'll make reasonable efforts to let you know before
          changes that affect an active subscription.
        </Bullet>
      </Section>

      <Section title="Acceptable use">
        <Bullet>
          Don't use Ollie for anything illegal, to harass or harm others, or to attempt to extract, abuse, or
          manipulate the underlying AI systems in ways that violate these terms.
        </Bullet>
        <Bullet>Don't try to access other users' accounts or data, reverse-engineer the app, or interfere with the service's normal operation.</Bullet>
        <Bullet>We may suspend or terminate accounts that violate these terms.</Bullet>
      </Section>

      <Section title="Your content">
        <Bullet>
          You own what you send Ollie. Using the app gives us permission to process your messages as described in
          the Privacy Policy — to generate replies, remember context, and run safety screening.
        </Bullet>
        <Bullet>Ollie's replies are generated by AI and may sometimes be inaccurate, out of character, or inappropriate. Use your own judgment.</Bullet>
      </Section>

      <Section title="Your account">
        <Bullet>
          You can delete your account at any time from Settings. Deletion goes through a short grace period before
          it's permanent — see the in-app deletion flow for exact details.
        </Bullet>
        <Bullet>
          If you have an active Premium subscription, deleting your account doesn't automatically cancel billing —
          cancel separately through Lemon Squeezy (use the link in your receipt email, or contact us).
        </Bullet>
      </Section>

      <Section title="Disclaimers">
        <Bullet>
          Ollie is provided "as is," without warranties of any kind. We don't guarantee the app will be
          uninterrupted, error-free, or that Ollie's responses will always be accurate or appropriate.
        </Bullet>
        <Bullet>
          To the fullest extent permitted by law, we aren't liable for indirect, incidental, or consequential damages
          arising from your use of the app, or for the content of Ollie's AI-generated responses.
        </Bullet>
      </Section>

      <Section title="Changes to these terms">
        <Bullet>
          If these terms change in a way that matters, we'll let you know in the app. Continuing to use Ollie after a
          change means you accept the updated terms.
        </Bullet>
      </Section>

      <Section title="Governing law">
        <Bullet>[Insert governing law / jurisdiction here before publishing.]</Bullet>
      </Section>

      <Section title="Contact us">
        <Bullet>Questions about these terms: [add a real contact email before publishing].</Bullet>
      </Section>
    </LegalPage>
  );
}
